language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y subversion git build-essential
  - sudo apt-get install -y automake qt4-dev-tools bison++ libginac-dev libboost-dev libboost-test-dev
  - svn checkout svn://svn.code.sf.net/p/powerdevs/code/trunk powerdevs-code
  - svn checkout svn://svn.code.sf.net/p/modelicacc/code/trunk modelicacc-code
before_script:
  - bison++ -V
  - cd modelicacc-code ; autoreconf -f ; ./configure ; make ; sudo make install 
  - cd powerdevs-code ; make 
script:
  - make 
branches:
  only:
    - master
