language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yq subversion git build-essential automake qt4-dev-tools bison++ libginac-dev libboost-dev libboost-test-dev

before_script:
  - svn checkout svn://svn.code.sf.net/p/modelicacc/code/trunk modelicacc-code
  - cd modelicacc-code ; autoreconf -f ; ./configure ; make ; sudo make install 
  - svn checkout svn://svn.code.sf.net/p/powerdevs/code/trunk powerdevs-code
  - cd powerdevs-code ; make install-lib
script:
  - make 
branches:
  only:
    - master
