language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install subversion git build-essential
  - sudo apt-get install automake
  - sudo apt-get install qt4-dev-tools
  - sudo apt-get install bison++ 
  - sudo apt-get install libginac-dev
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-test-dev
  - svn checkout svn://svn.code.sf.net/p/powerdevs/code/trunk powerdevs-code
  - svn checkout svn://svn.code.sf.net/p/modelicacc/code/trunk modelicacc-code
before_script:
  - cd modelicacc-code ; make ; sudo make install 
  - cd powerdevs-code ; make 
script:
  - make 
branches:
  only:
    - master
