doc: tesina.md
	pandoc -o tesina.pdf tesina.md -V biblio-title=Bibliografía -V biblio-files=extra/biblio -V biblatex --template=extra/template.tex
	pandoc -o tesina.tex tesina.md -V biblio-title=Bibliografía -V biblio-files=extra/biblio -V biblatex --template=extra/template.tex

